import {
  Box,
  Button,
  Container,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  Stack,
  Text,
  Textarea,
} from "@chakra-ui/react";
import { useState } from "react";
import {
  useCreateCsrfPayloadMutation,
  useGetMeQuery,
  useListCsrfPayloadsQuery,
  useUpdateUserMutation,
} from "../store/api";

const CSRF_Example = `
<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
    <form action="http://195.208.26.67:8000/admin/">
      <input type="submit" value="Submit request" />
    </form>
    <script>
      history.pushState('', '', '/');
      document.forms[0].submit();
    </script>
  </body>
</html>
`;

function MainPage() {
  const { data, isLoading } = useGetMeQuery();
  const [updateUser, { isLoading: isSaving }] = useUpdateUserMutation();
  const [createCsrfPayload, { isLoading: isSavingCsrf }] =
    useCreateCsrfPayloadMutation();
  const { data: csrfListData } = useListCsrfPayloadsQuery();
  const defaultCsrfPayload =
    csrfListData?.items?.[0]?.payload ?? CSRF_Example;

  const [xssPath, setXssPath] = useState("");
  const [csrfPath, setCsrfPath] = useState("");
  const [editingPaths, setEditingPaths] = useState(false);

  const [oldPassword, setOldPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [passwordError, setPasswordError] = useState<string | null>(null);

  const [csrfPayload, setCsrfPayload] = useState("");
  const [jsPayload, setJsPayload] = useState("");
  const [csrfError, setCsrfError] = useState<string | null>(null);

  async function handleSavePaths() {
    if (!data?.user) return;
    await updateUser({
      nickname: data.user.nickname,
      xssPath,
      csrfPath,
    }).unwrap();
    setEditingPaths(false);
  }

  async function handleChangePassword() {
    if (!data?.user) return;
    setPasswordError(null);
    if (!oldPassword || !newPassword) {
      setPasswordError("Old and new password are required.");
      return;
    }
    if (newPassword !== confirmPassword) {
      setPasswordError("Passwords do not match.");
      return;
    }
    await updateUser({
      nickname: data.user.nickname,
      password: newPassword,
      oldPassword,
    }).unwrap();
    setOldPassword("");
    setNewPassword("");
    setConfirmPassword("");
  }

  async function handleSaveCsrfPayload() {
    setCsrfError(null);
    if (!csrfPayload.trim()) {
      setCsrfError("CSRF payload is required.");
      return;
    }
    try {
      await createCsrfPayload({ payload: csrfPayload.trim() }).unwrap();
    } catch {
      setCsrfError("Failed to save CSRF payload.");
    }
  }

  if (isLoading) {
    return (
      <Flex minH="100vh" align="center" justify="center">
        <Text>Loading...</Text>
      </Flex>
    );
  }

  if (!data?.user) {
    return (
      <Flex minH="100vh" align="center" justify="center">
        <Text>Unauthorized</Text>
      </Flex>
    );
  }

  const user = data.user;
  const displayedXssPath = editingPaths ? xssPath : user.xssPath;
  const displayedCsrfPath = editingPaths ? csrfPath : user.csrfPath;

  return (
    <Box bg="gray.50" minH="100vh" py="6">
      <Container maxW="full" px={{ base: "2", md: "3", xl: "4" }}>
        <Stack gap="6">
          <Heading size="lg">Dashboard</Heading>

          <Grid templateColumns={"repeat(11, 1fr)"} gap="6">
            <GridItem colSpan={2}>
              <Box
                bg="white"
                borderRadius="xl"
                borderWidth="1px"
                p="6"
                boxShadow="sm"
              >
                <Stack gap="4">
                  <Heading size="md">Callback paths</Heading>

                  <Stack gap="2">
                    <Text fontSize="sm" color="gray.600">
                      XSS callback
                    </Text>
                    <Input
                      value={displayedXssPath}
                      onChange={(event) => setXssPath(event.target.value)}
                      disabled={!editingPaths}
                    />
                  </Stack>

                  <Stack gap="2">
                    <Text fontSize="sm" color="gray.600">
                      CSRF callback
                    </Text>
                    <Input
                      value={displayedCsrfPath}
                      onChange={(event) => setCsrfPath(event.target.value)}
                      disabled={!editingPaths}
                    />
                  </Stack>

                  <Flex gap="3">
                    {editingPaths ? (
                      <>
                        <Button
                          colorScheme="blue"
                          onClick={handleSavePaths}
                          loading={isSaving}
                        >
                          Save
                        </Button>
                        <Button
                          variant="ghost"
                          onClick={() => {
                            setXssPath(user.xssPath);
                            setCsrfPath(user.csrfPath);
                            setEditingPaths(false);
                          }}
                        >
                          Cancel
                        </Button>
                      </>
                    ) : (
                      <Button
                        variant="outline"
                        onClick={() => {
                          setXssPath(user.xssPath);
                          setCsrfPath(user.csrfPath);
                          setEditingPaths(true);
                        }}
                      >
                        Edit
                      </Button>
                    )}
                  </Flex>

                  <Box borderTopWidth="1px" pt="4">
                    <Heading size="sm" mb="3">
                      Change password
                    </Heading>
                    <Stack gap="3">
                      <Input
                        type="password"
                        placeholder="Old password"
                        value={oldPassword}
                        onChange={(event) => setOldPassword(event.target.value)}
                      />
                      <Input
                        type="password"
                        placeholder="New password"
                        value={newPassword}
                        onChange={(event) => setNewPassword(event.target.value)}
                      />
                      <Input
                        type="password"
                        placeholder="Confirm new password"
                        value={confirmPassword}
                        onChange={(event) =>
                          setConfirmPassword(event.target.value)
                        }
                      />
                      {passwordError ? (
                        <Text fontSize="sm" color="red.500">
                          {passwordError}
                        </Text>
                      ) : null}
                      <Button
                        colorScheme="blue"
                        onClick={handleChangePassword}
                        loading={isSaving}
                      >
                        Update password
                      </Button>
                    </Stack>
                  </Box>
                </Stack>
              </Box>
            </GridItem>
            <GridItem colSpan={3}>
              <Box
                bg="white"
                borderRadius="xl"
                borderWidth="1px"
                p="6"
                boxShadow="sm"
              >
                <Stack gap="4">
                  <Heading size="md">CSRF HTML payload</Heading>
                  <Textarea
                    minH="220px"
                    placeholder="Paste HTML payload here"
                    value={csrfPayload || defaultCsrfPayload}
                    onChange={(event) => setCsrfPayload(event.target.value)}
                  />
                  {csrfError ? (
                    <Text fontSize="sm" color="red.500">
                      {csrfError}
                    </Text>
                  ) : null}
                  <Button
                    variant="outline"
                    onClick={handleSaveCsrfPayload}
                    loading={isSavingCsrf}
                  >
                    Save payload
                  </Button>
                </Stack>
              </Box>
            </GridItem>

            <GridItem colSpan={3}>
              <Box
                bg="white"
                borderRadius="xl"
                borderWidth="1px"
                p="6"
                boxShadow="sm"
              >
                <Stack gap="4">
                  <Heading size="md">XSS payload generator</Heading>
                  <Textarea
                    minH="140px"
                    placeholder="Write JS payload here"
                    value={jsPayload}
                    onChange={(event) => setJsPayload(event.target.value)}
                  />
                  <Textarea
                    minH="180px"
                    placeholder="Generated XSS payloads will appear here"
                    value=""
                    readOnly
                  />
                  <Text fontSize="xs" color="gray.500">
                    JS payload is stored in local state for now.
                  </Text>
                </Stack>
              </Box>
            </GridItem>
            <GridItem colSpan={3}>
              <Box
                bg="white"
                borderRadius="xl"
                borderWidth="1px"
                p="6"
                boxShadow="sm"
              >
                <Stack gap="4">
                  <Heading size="md">Callback activity</Heading>
                  <Text fontSize="sm" color="gray.600">
                    Here you will see if someone opened your CSRF/XSS links.
                  </Text>
                  <Stack gap="3" fontSize="sm" color="gray.700">
                    <Text>No events yet.</Text>
                  </Stack>
                </Stack>
              </Box>
            </GridItem>
          </Grid>
        </Stack>
      </Container>
    </Box>
  );
}

export default MainPage;
